### ISSUE TITLE
save a fully-scraped version

### ISSUE THREAD

**Issue by lwaldron** [JonathanYe3/bergeys.webscraper#6]
You can just do a simple:

```
res <- readBmanual(a=1, b=howevermanythereare) 
save(res, file="~/Downloads/bergeys.rda", compress="xz")
```

make sure there's `LazyData: TRUE` in the DESCRIPTION, and document the data as in https://github.com/waldronlab/HGNChelper/blob/master/R/data.R. Then use `readBmanual` only to update to update the package dataset, and document using the stored data for normal use to be faster, provide reproducible versioned data, and avoid frequent scraping.

**Comment by JonathanYe3** [comment]
Alright, I think I have finally completed this step.
